<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<section class="studio-hero" aria-labelledby="welcome-title">
  <div class="studio-hero-copy">
    <p class="studio-kicker"><span class="kicker-square" aria-hidden="true"></span> THE CREATIVE COUNTER <span class="kicker-rule" aria-hidden="true"></span> <?= esc(strtoupper(date('F j, Y', strtotime($today)))) ?></p>
    <h1 id="welcome-title">Make it<br><span class="type-outline">print.</span> <span class="type-orange">Make it</span><br>count<span class="hero-period">.</span></h1>
    <p class="studio-lede">A print and supply shop for the work that needs to get done. From the first page to the final pickup, our day runs on clear details and a ready team.</p>
    <div class="hero-actions"><a class="button button-dark" href="#todays-work">Explore today’s work <span aria-hidden="true">↗</span></a><a class="button button-outline" href="<?= site_url('tasks') ?>">Open task board <span aria-hidden="true">→</span></a></div>
    <div class="studio-hero-foot"><span class="hero-line" aria-hidden="true"></span><span>PRINTING <b>•</b> STATIONERY <b>•</b> THE DETAILS IN BETWEEN</span></div>
  </div>
  <div class="studio-scene" aria-label="An illustrated sample print order with paper and stationery">
    <div class="scene-grid" aria-hidden="true"></div>
    <div class="scene-sheet scene-sheet-back" aria-hidden="true"><span>LEDGERLINE</span><strong>IDEAS<br>LOOK<br>BETTER<br>ON PAPER.</strong><i>PRINT / SUPPLY</i></div>
    <div class="scene-sheet scene-sheet-front" aria-hidden="true"><span class="sheet-top">SAMPLE PRINT / 001</span><div class="sheet-mark">L<span>.</span></div><div class="sheet-bars"><i></i><i></i><i></i></div><span class="sheet-bottom">THE DETAILS MAKE THE DIFFERENCE</span></div>
    <div class="scene-pencil" aria-hidden="true"></div>
    <div class="scene-sticker" aria-hidden="true"><span>READY<br>FOR THE<br>COUNTER</span><svg viewBox="0 0 36 36"><path d="M5 18h25m-9-9 9 9-9 9" fill="none" stroke="currentColor" stroke-width="2"/></svg></div>
    <div class="scene-caption" aria-hidden="true">A little more thought. A much better finish.</div>
  </div>
</section>
<div class="service-ribbon" aria-label="Shop focus areas"><span>PRINT</span><b aria-hidden="true">✳</b><span>PREPARE</span><b aria-hidden="true">✳</b><span>SUPPLY</span><b aria-hidden="true">✳</b><span>DELIVER</span><b aria-hidden="true">✳</b><span>PRINT</span></div>
<section class="studio-intro" data-reveal aria-labelledby="intro-title"><div><p class="eyebrow">THE SHOP AT A GLANCE</p><h2 id="intro-title">Built for the <em>little things</em><br>that make a big difference.</h2></div><p>Documents that need to be crisp. Supplies that need to be in stock. Orders that need to be ready when promised. Ledgerline keeps the counter moving.</p></section>
<section class="shop-stats" aria-label="Shop record counts"><div><span>01 / TODAY’S WORK</span><strong><?= count($tasks) ?></strong><p>tasks scheduled today</p></div><div><span>02 / CUSTOMERS</span><strong><?= esc($customerCount) ?></strong><p>customer records</p></div><div><span>03 / SHOP TEAM</span><strong><?= esc($userCount) ?></strong><p>staff records</p></div></section>
<section class="studio-services" aria-label="What the shop handles"><article data-reveal class="service-card service-card-blue"><span class="service-index">01 / PRINT</span><div class="service-art service-art-paper" aria-hidden="true"><i></i><i></i><i></i></div><div><h3>From file<br>to finish.</h3><p>Clear specifications keep each print job on track.</p></div></article><article data-reveal class="service-card service-card-orange"><span class="service-index">02 / PREPARE</span><div class="service-art service-art-stack" aria-hidden="true"><i></i><i></i><i></i></div><div><h3>Ready when<br>you are.</h3><p>Check, pack, and prepare each order for pickup.</p></div></article><article data-reveal class="service-card service-card-cream"><span class="service-index">03 / SUPPLY</span><div class="service-art service-art-supply" aria-hidden="true"><i></i><i></i><i></i></div><div><h3>Everyday<br>essentials.</h3><p>Paper and stationery are part of the daily rhythm.</p></div></article></section>
<section class="today-section" id="todays-work" aria-labelledby="today-title"><div class="section-top"><div><p class="eyebrow">LIVE FROM THE TASK BOARD</p><h2 id="today-title">The work behind <em>the counter.</em></h2><p>Scheduled for <?= esc(date('F j, Y', strtotime($today))) ?>.</p></div><a class="inline-link" href="<?= site_url('tasks') ?>">View the full board <span aria-hidden="true">↗</span></a></div>
<?php if ($tasks === []): ?><div class="empty-state"><strong>The desk is clear today.</strong><p>Check the task board for work on other dates.</p></div><?php else: ?>
<?php $completedToday = count(array_filter($tasks, static fn (array $task): bool => $task['status'] === 'completed')); ?>
<div class="daily-progress"><div><span>DAILY PROGRESS</span><strong><?= $completedToday ?> of <?= count($tasks) ?> tasks complete</strong></div><progress value="<?= $completedToday ?>" max="<?= count($tasks) ?>"><?= $completedToday ?> of <?= count($tasks) ?></progress></div>
<div class="task-list"><?php foreach ($tasks as $index => $task): ?><article class="task-item"><span class="task-number"><?= esc(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)) ?></span><div class="task-copy"><h3><?= esc($task['title']) ?></h3><span>Shop desk · <?= esc(date('M j', strtotime($task['task_date']))) ?></span></div><span class="status status-<?= esc(str_replace(' ', '-', $task['status'])) ?>"><?= esc(ucwords($task['status'])) ?></span><?php if (session()->get('staff_id')): ?><a class="inline-link task-edit" href="<?= site_url('tasks/' . $task['id'] . '/edit') ?>" aria-label="Edit <?= esc($task['title'], 'attr') ?>">Edit ↗</a><?php endif ?></article><?php endforeach ?></div><?php endif ?></section>
<section class="studio-endcap" data-reveal aria-labelledby="endcap-title"><div><p class="eyebrow">KEEP THINGS MOVING</p><h2 id="endcap-title">One good day<br><em>at a time.</em></h2></div><div><p>See the full task schedule or sign in to manage the details behind each working day.</p><a class="button button-dark" href="<?= site_url('tasks') ?>">Visit the task board <span aria-hidden="true">↗</span></a></div><span class="endcap-letter" aria-hidden="true">L</span></section>
<?php if (session()->get('staff_id')): ?><section class="shop-paths" aria-label="Explore shop records"><a href="<?= site_url('customers') ?>"><span class="path-icon" aria-hidden="true">C</span><span><small>SHOP RECORDS</small><strong>Customers</strong><em>Find the people behind the orders.</em></span><b aria-hidden="true">↗</b></a><a href="<?= site_url('users') ?>"><span class="path-icon" aria-hidden="true">S</span><span><small>SHOP TEAM</small><strong>Staff directory</strong><em>Keep the counter team in view.</em></span><b aria-hidden="true">↗</b></a></section><?php else: ?><section class="shop-paths shop-paths-single" aria-label="Staff access"><a href="<?= site_url('login') ?>"><span class="path-icon" aria-hidden="true">↗</span><span><small>STAFF ACCESS</small><strong>Sign in to manage the shop</strong><em>Create and update tasks, and view shop records.</em></span><b aria-hidden="true">↗</b></a></section><?php endif ?>
<?= $this->endSection() ?>
